spring:
    application:
        name: reading-client-circruit-breaker
    output:
        ansi:
            enabled: always
server:
  port: 8085

eureka:
  client:
    service-url: 
        defaultZone: http://localhost:8991/eureka

logging:
  level:
    # netflix discovery
    '[com.netflix.discovery.shared.resolver]': warn

